import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { MeasurementResult } from '../types';

export const generateMeasurementReport = (result: MeasurementResult): void => {
    const doc = new jsPDF();

    // Colors
    const bronze: [number, number, number] = [184, 134, 11];
    const silver: [number, number, number] = [192, 192, 192];
    const midnight: [number, number, number] = [15, 23, 42];

    // Header - LUNE Branding
    doc.setFillColor(...bronze);
    doc.rect(0, 0, 210, 40, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(32);
    doc.setFont('helvetica', 'bold');
    doc.text('LUNE', 105, 25, { align: 'center' });
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.text('AI-Powered Ring Sizing Report', 105, 33, { align: 'center' });

    // Reset text color
    doc.setTextColor(...midnight);

    // Date
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    const date = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
    doc.text(`Generated: ${date}`, 20, 50);

    // Main Results Section
    doc.setFontSize(16);
    doc.setTextColor(...midnight);
    doc.setFont('helvetica', 'bold');
    doc.text('Your Ring Size', 20, 65);

    doc.setFontSize(24);
    doc.setTextColor(...bronze);
    doc.text(`US ${result.ringSize.us}`, 20, 78);

    doc.setFontSize(12);
    doc.setTextColor(...midnight);
    doc.setFont('helvetica', 'normal');
    doc.text(`UK: ${result.ringSize.uk} | EU: ${result.ringSize.eu}`, 20, 86);

    // Measurement Details
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Measurement Details', 20, 100);

    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    doc.text(`Finger Diameter: ${result.fingerDiameter_mm.toFixed(2)} mm`, 20, 110);
    doc.text(`Finger Circumference: ${result.fingerCircumference_mm.toFixed(2)} mm`, 20, 118);
    doc.text(`Confidence Level: ${result.confidence}%`, 20, 126);

    if (result.handProfile) {
        doc.text(`Hand Profile: ${result.handProfile.gender.charAt(0).toUpperCase() + result.handProfile.gender.slice(1)} - ${result.handProfile.size.toUpperCase()}`, 20, 134);
    }

    // Ring Size Conversion Chart
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Universal Ring Size Chart', 20, 150);

    autoTable(doc, {
        startY: 155,
        head: [['US Size', 'UK Size', 'EU Size', 'Diameter (mm)', 'Circumference (mm)']],
        body: [
            ['4', 'H', '47', '14.9', '46.8'],
            ['5', 'J', '49', '15.7', '49.3'],
            ['6', 'L', '51', '16.5', '51.9'],
            ['7', 'N', '54', '17.3', '54.4'],
            ['8', 'P', '57', '18.2', '57.0'],
            ['9', 'R', '59', '19.0', '59.5'],
            ['10', 'T', '62', '19.8', '62.1'],
            ['11', 'V', '64', '20.6', '64.6'],
            ['12', 'X', '67', '21.4', '67.2'],
        ],
        theme: 'striped',
        headStyles: { fillColor: bronze, textColor: [255, 255, 255], fontStyle: 'bold' },
        styles: { fontSize: 9, cellPadding: 3 },
        columnStyles: {
            0: { halign: 'center' },
            1: { halign: 'center' },
            2: { halign: 'center' },
            3: { halign: 'center' },
            4: { halign: 'center' },
        },
    });

    // Footer
    const pageHeight = doc.internal.pageSize.height;
    doc.setFontSize(9);
    doc.setTextColor(150, 150, 150);
    doc.text('This report is for reference only. For best results, verify your size with a jeweler.', 105, pageHeight - 20, { align: 'center' });
    doc.text('Generated by LUNE - AI-Powered Ring Sizing', 105, pageHeight - 15, { align: 'center' });
    doc.setTextColor(...bronze);
    doc.text('www.lune-sizing.com', 105, pageHeight - 10, { align: 'center' });

    // Save the PDF
    doc.save(`LUNE-Ring-Size-Report-US${result.ringSize.us}.pdf`);
};
