import React, { useState } from 'react';
import { Button } from '../Button';
import { Card } from '../Card';
import { ArrowLeftIcon, DownloadIcon, PrinterIcon, CheckCircleIcon, AlertTriangleIcon } from '../icons/UtilIcons';
import { RING_SIZE_TABLE } from '../../lib/sizeConversion';
import { jsPDF } from 'jspdf';

interface PrintableSizerProps {
    onBack: () => void;
}

export const PrintableSizer = ({ onBack }: PrintableSizerProps) => {
    const [isGenerating, setIsGenerating] = useState(false);

    const generatePDF = () => {
        setIsGenerating(true);

        try {
            const doc = new jsPDF({
                orientation: 'portrait',
                unit: 'mm',
                format: 'a4'
            });

            const pageWidth = 210; // A4 width in mm
            const pageHeight = 297; // A4 height in mm
            const margin = 20;

            // Title
            doc.setFontSize(24);
            doc.setFont('helvetica', 'bold');
            doc.text('LUNE Ring Sizer', pageWidth / 2, margin, { align: 'center' });

            // Instructions
            doc.setFontSize(10);
            doc.setFont('helvetica', 'normal');
            const instructions = [
                'PRINTING INSTRUCTIONS:',
                '1. Print this page at 100% scale (NO SCALING)',
                '2. Verify the ruler below measures exactly 50mm',
                '3. Cut out the circles and place your existing ring inside',
                '4. The circle that matches your ring\'s inner edge is your size',
                '',
                'IMPORTANT: Do not use "Fit to Page" or any scaling options!'
            ];

            let yPos = margin + 15;
            instructions.forEach(line => {
                doc.text(line, margin, yPos);
                yPos += 5;
            });

            // Verification Ruler
            yPos += 5;
            doc.setFontSize(12);
            doc.setFont('helvetica', 'bold');
            doc.text('Scale Verification Ruler (50mm)', margin, yPos);

            yPos += 5;
            doc.setLineWidth(0.5);
            doc.rect(margin, yPos, 50, 10); // 50mm ruler box

            // Ruler markings
            for (let i = 0; i <= 50; i += 5) {
                const x = margin + i;
                doc.line(x, yPos, x, yPos + (i % 10 === 0 ? 10 : 5));
                if (i % 10 === 0) {
                    doc.setFontSize(8);
                    doc.text(i.toString(), x, yPos + 13, { align: 'center' });
                }
            }

            // Ring Size Circles
            yPos += 25;
            doc.setFontSize(12);
            doc.setFont('helvetica', 'bold');
            doc.text('Ring Size Circles', margin, yPos);

            yPos += 10;
            const circlesPerRow = 3;
            const circleSpacing = 60;
            let col = 0;
            let row = 0;

            // Generate circles for common sizes (3-13)
            // Fix TypeScript error by converting size.us to number
            const commonSizes = RING_SIZE_TABLE.filter(size =>
                Number(size.us) >= 3 && Number(size.us) <= 13 && Number(size.us) % 0.5 === 0
            );

            commonSizes.forEach((size, index) => {
                const x = margin + (col * circleSpacing) + 25;
                const y = yPos + (row * circleSpacing) + 25;

                // Draw circle (inner diameter)
                const radius = size.diameter_mm / 2;
                doc.setLineWidth(0.3);
                doc.circle(x, y, radius);

                // Size label
                doc.setFontSize(10);
                doc.setFont('helvetica', 'bold');
                doc.text(`US ${size.us}`, x, y - radius - 3, { align: 'center' });

                // UK/EU label
                doc.setFontSize(8);
                doc.setFont('helvetica', 'normal');
                doc.text(`UK ${size.uk} / EU ${size.eu}`, x, y - radius - 8, { align: 'center' });

                // Diameter label
                doc.text(`${size.diameter_mm}mm`, x, y + radius + 5, { align: 'center' });

                col++;
                if (col >= circlesPerRow) {
                    col = 0;
                    row++;
                }

                // Add new page if needed
                if (row >= 4 && index < commonSizes.length - 1) {
                    doc.addPage();
                    yPos = margin;
                    row = 0;
                    col = 0;
                }
            });

            // Footer
            doc.setFontSize(8);
            doc.setFont('helvetica', 'italic');
            doc.text('Generated by LUNE - Your Perfect Fit, Captured in Light', pageWidth / 2, pageHeight - 10, { align: 'center' });

            // Save PDF
            doc.save('LUNE-Ring-Sizer.pdf');

        } catch (error) {
            console.error('Error generating PDF:', error);
            alert('Failed to generate PDF. Please try again.');
        } finally {
            setIsGenerating(false);
        }
    };

    return (
        <div className="min-h-screen w-full bg-midnight-600 relative overflow-hidden flex flex-col">
            {/* Background Elements */}
            <div className="absolute top-0 left-0 w-full h-full overflow-hidden pointer-events-none">
                <div className="absolute top-[-10%] right-[-10%] w-[600px] h-[600px] bg-bronze-500/10 rounded-full blur-[120px]"></div>
                <div className="absolute bottom-[-10%] left-[-10%] w-[500px] h-[500px] bg-indigo-500/10 rounded-full blur-[100px]"></div>
                <div className="absolute inset-0 bg-[url('https://grainy-gradients.vercel.app/noise.svg')] opacity-20 mix-blend-overlay"></div>
            </div>

            <div className="relative z-10 container mx-auto px-4 md:px-6 py-8 md:py-12 flex-grow flex flex-col max-w-5xl">
                {/* Header */}
                <div className="flex items-center gap-4 mb-8">
                    <button
                        onClick={onBack}
                        className="flex items-center justify-center w-12 h-12 rounded-full bg-white/5 border border-white/10 hover:bg-white/10 hover:border-white/20 transition-all duration-300 group"
                        aria-label="Go back"
                    >
                        <ArrowLeftIcon className="h-5 w-5 text-silver-300 group-hover:text-white group-hover:-translate-x-0.5 transition-all" />
                    </button>
                    <div>
                        <h1 className="font-display text-3xl md:text-4xl lg:text-5xl text-white mb-1">Printable Ring Sizer</h1>
                        <p className="text-silver-400 text-base md:text-lg">Download and print at home</p>
                    </div>
                </div>

                <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 flex-grow">
                    {/* Instructions Card */}
                    <Card className="flex flex-col">
                        <div className="flex items-center gap-3 mb-6">
                            <div className="p-3 bg-bronze-400/20 rounded-full">
                                <PrinterIcon className="w-6 h-6 text-bronze-400" />
                            </div>
                            <h2 className="text-2xl font-display text-white">How It Works</h2>
                        </div>

                        <div className="space-y-6 flex-grow">
                            <div className="flex gap-4">
                                <div className="flex-shrink-0 w-8 h-8 rounded-full bg-bronze-400 text-white flex items-center justify-center font-bold">
                                    1
                                </div>
                                <div>
                                    <h3 className="text-lg font-semibold text-white mb-2">Download PDF</h3>
                                    <p className="text-silver-400 text-sm">Click the button below to download the printable ring sizer PDF.</p>
                                </div>
                            </div>

                            <div className="flex gap-4">
                                <div className="flex-shrink-0 w-8 h-8 rounded-full bg-bronze-400 text-white flex items-center justify-center font-bold">
                                    2
                                </div>
                                <div>
                                    <h3 className="text-lg font-semibold text-white mb-2">Print at 100% Scale</h3>
                                    <p className="text-silver-400 text-sm">
                                        Print the PDF at <span className="text-white font-semibold">100% scale</span> with no scaling or "fit to page" options.
                                    </p>
                                </div>
                            </div>

                            <div className="flex gap-4">
                                <div className="flex-shrink-0 w-8 h-8 rounded-full bg-bronze-400 text-white flex items-center justify-center font-bold">
                                    3
                                </div>
                                <div>
                                    <h3 className="text-lg font-semibold text-white mb-2">Verify Scale</h3>
                                    <p className="text-silver-400 text-sm">
                                        Use a ruler to verify the printed ruler measures exactly <span className="text-white font-semibold">50mm</span>.
                                    </p>
                                </div>
                            </div>

                            <div className="flex gap-4">
                                <div className="flex-shrink-0 w-8 h-8 rounded-full bg-bronze-400 text-white flex items-center justify-center font-bold">
                                    4
                                </div>
                                <div>
                                    <h3 className="text-lg font-semibold text-white mb-2">Find Your Size</h3>
                                    <p className="text-silver-400 text-sm">
                                        Place an existing ring inside the circles. The circle that matches your ring's inner edge is your size.
                                    </p>
                                </div>
                            </div>
                        </div>

                        <Button
                            onClick={generatePDF}
                            isLoading={isGenerating}
                            className="w-full mt-6"
                            icon={<DownloadIcon className="w-5 h-5" />}
                        >
                            {isGenerating ? 'Generating PDF...' : 'Download Ring Sizer PDF'}
                        </Button>
                    </Card>

                    {/* Tips Card */}
                    <Card className="flex flex-col">
                        <div className="flex items-center gap-3 mb-6">
                            <div className="p-3 bg-green-500/20 rounded-full">
                                <CheckCircleIcon className="w-6 h-6 text-green-400" />
                            </div>
                            <h2 className="text-2xl font-display text-white">Tips for Accuracy</h2>
                        </div>

                        <div className="space-y-4 flex-grow">
                            <div className="p-4 bg-white/5 rounded-lg border border-white/10">
                                <h4 className="text-sm font-semibold text-white mb-2">✓ Print Settings</h4>
                                <ul className="text-sm text-silver-400 space-y-1">
                                    <li>• Use "Actual Size" or "100%" scaling</li>
                                    <li>• Disable "Fit to Page"</li>
                                    <li>• Use standard A4 paper</li>
                                </ul>
                            </div>

                            <div className="p-4 bg-white/5 rounded-lg border border-white/10">
                                <h4 className="text-sm font-semibold text-white mb-2">✓ Measurement Tips</h4>
                                <ul className="text-sm text-silver-400 space-y-1">
                                    <li>• Use a ring that fits comfortably</li>
                                    <li>• Measure at room temperature</li>
                                    <li>• Check multiple times for consistency</li>
                                </ul>
                            </div>

                            <div className="p-4 bg-white/5 rounded-lg border border-white/10">
                                <h4 className="text-sm font-semibold text-white mb-2">✓ What's Included</h4>
                                <ul className="text-sm text-silver-400 space-y-1">
                                    <li>• US sizes 3-13 (half sizes included)</li>
                                    <li>• UK and EU size conversions</li>
                                    <li>• 50mm verification ruler</li>
                                    <li>• Diameter measurements</li>
                                </ul>
                            </div>

                            <div className="p-4 bg-yellow-500/10 border border-yellow-500/30 rounded-lg">
                                <div className="flex items-start gap-2">
                                    <AlertTriangleIcon className="w-5 h-5 text-yellow-400 mt-0.5 flex-shrink-0" />
                                    <div>
                                        <h4 className="text-sm font-semibold text-yellow-300 mb-1">Important</h4>
                                        <p className="text-xs text-silver-400">
                                            Always verify the ruler measures exactly 50mm before using the sizer. Incorrect print scaling will result in inaccurate measurements.
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </Card>
                </div>
            </div>
        </div>
    );
};
